# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from minecraft.manifest import get_versions

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Titulo = QtWidgets.QLabel(self.centralwidget)
        self.Titulo.setGeometry(QtCore.QRect(270, 40, 247, 52))

        font = QtGui.QFont()
        font.setPointSize(32)

        self.Titulo.setFont(font)
        self.Titulo.setObjectName("Titulo")

        self.versions = QtWidgets.QComboBox(self.centralwidget)
        self.versions.setGeometry(QtCore.QRect(330, 270, 101, 22))
        self.versions.setObjectName("versions")
        
        self.versions.addItems(get_versions())

        self.userInput = QtWidgets.QLineEdit(self.centralwidget)
        self.userInput.setGeometry(QtCore.QRect(330, 160, 113, 20))
        self.userInput.setObjectName("userInput")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 130, 51, 20))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 190, 51, 20))
        self.label_2.setObjectName("label_2")

        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(330, 220, 113, 20))
        self.passwordInput.setObjectName("passwordInput")

        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(350, 330, 75, 23))
        self.playButton.setObjectName("playButton")
        self.playButton.clicked.connect(self.on_playButton_clicked)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)

        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def on_playButton_clicked(self):
        user = self.userInput.text()
        password = self.passwordInput.text()
        version = self.versions.currentText()
        print(f"user: {user}")
        print(f"password: {password}")
        print(f"version: {version}")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titulo.setText(_translate("MainWindow", "MC Launcher"))
        self.label.setText(_translate("MainWindow", "user"))
        self.label_2.setText(_translate("MainWindow", "password"))
        self.playButton.setText(_translate("MainWindow", "PLAY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())