# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(967, 572)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Titulo = QtWidgets.QLabel(self.centralwidget)
        self.Titulo.setGeometry(QtCore.QRect(360, 40, 311, 52))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.Titulo.setFont(font)
        self.Titulo.setObjectName("Titulo")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 470, 1241, 80))
        self.frame.setAutoFillBackground(True)
        self.frame.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.playButton = QtWidgets.QPushButton(self.frame)
        self.playButton.setGeometry(QtCore.QRect(610, 10, 171, 51))
        self.playButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playButton.setStyleSheet(".QPushButton{\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius:5px;\n"
"font: 100 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
".QPushButton:hover{\n"
"background-color:rgb(255, 85, 0);\n"
"}")
        self.playButton.setObjectName("playButton")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(220, 20, 281, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.versions = QtWidgets.QComboBox(self.widget)
        self.versions.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.versions.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.versions.setObjectName("versions")
        self.horizontalLayout.addWidget(self.versions)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(390, 220, 139, 49))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.passwordInput = QtWidgets.QLineEdit(self.widget1)
        self.passwordInput.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(390, 160, 139, 49))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.userInput = QtWidgets.QLineEdit(self.widget2)
        self.userInput.setObjectName("userInput")
        self.verticalLayout_2.addWidget(self.userInput)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titulo.setText(_translate("MainWindow", "MC Launcher"))
        self.playButton.setText(_translate("MainWindow", "Enter the game"))
        self.label_3.setText(_translate("MainWindow", "Version:"))
        self.label_2.setText(_translate("MainWindow", "password"))
        self.label.setText(_translate("MainWindow", "user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
